### ISSUE TITLE
Add loading screen

### ISSUE THREAD

**Issue by Bunyod16** [Bunyod16/42-on_campus_stats#21]
When the backend api hasnt been called for a while, it goes into sleep mode. So if someone decides to call it, it will need some time to gather all the data. Depending on the amount of users, this time can range from 20sec-N min.

The proposal is to add an initial loading screen and keep calling the current_active_users end point every 5-10 seconds until data is returned.

**Comment by Bunyod16** [comment]
Alternatively we can just add loading spinners to each component while the request has not been processed

**Comment by jasonkwm** [comment]
Issue has been resolved! All thanks to senpai Jaclyn
