### ISSUE TITLE
Cadets to Piscine ratio bar seems a bit broken

### ISSUE THREAD

**Issue by dastrukar** [Bunyod16/42-on_campus_stats#31]
The bar seems a bit broken now that there are no pisciners:
![image](https://user-images.githubusercontent.com/32709291/222955680-5e9331a1-4970-49d8-9d27-82df227f6ec7.png)

Also, shouldn't it be "Pisciners", not "Piscine"?

**Comment by Bunyod16** [comment]
You’re welcome to fix it

**Comment by jasonkwm** [comment]
Problemo Solve
